CREATE DATABASE 'localhost:C:\dev\Firebird-2.1.3.18185-0\dbmasterdetail\MAESTRODETALLE001.FDB'
USER 'SYSDBA' PASSWORD '**********'
PAGE_SIZE 16384
DEFAULT CHARACTER SET UTF8;

/* Generators */
CREATE SEQUENCE GEN_DEPARTMENT_ID;

ALTER SEQUENCE GEN_DEPARTMENT_ID RESTART WITH 2;
CREATE SEQUENCE GEN_EMPLOYEE_ID;

ALTER SEQUENCE GEN_EMPLOYEE_ID RESTART WITH 11;

/* Tables */
CREATE TABLE DEPARTMENT (
  DEPT_NO     INTEGER NOT NULL,
  DEPARTMENT  VARCHAR(25) NOT NULL,
  HEAD_DEPT   INTEGER,
  LOCATION    VARCHAR(15),
  PHONE_NO    VARCHAR(15)
) ;

CREATE TABLE EMPLOYEE (
  EMP_NO      INTEGER NOT NULL,
  FIRST_NAME  VARCHAR(15) NOT NULL,
  LAST_NAME   VARCHAR(15) NOT NULL,
  PHONE_EXT   VARCHAR(4),
  HIRE_DATE   TIMESTAMP DEFAULT 'NOW' NOT NULL,
  DEPT_NO     INTEGER NOT NULL,
  FULL_NAME   COMPUTED BY (last_name || ', ' || first_name)
) ;
COMMIT;

/* Constraints */
ALTER TABLE DEPARTMENT
  ADD CONSTRAINT PK_DEPARTMENT
  PRIMARY KEY (DEPT_NO);

ALTER TABLE EMPLOYEE
  ADD CONSTRAINT PK_EMPLOYEE
  PRIMARY KEY (EMP_NO);

COMMIT;
/* Foreign Keys */
ALTER TABLE EMPLOYEE
  ADD CONSTRAINT EMPLOYEE_FOREIGN_KEY01
  FOREIGN KEY (DEPT_NO)
    REFERENCES DEPARTMENT(DEPT_NO)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

/* Triggers */
SET TERM ^ ;
CREATE TRIGGER DEPARTMENT_BI FOR DEPARTMENT
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.DEPT_NO IS NULL) THEN
    NEW.DEPT_NO = GEN_ID(GEN_DEPARTMENT_ID,1);
END^

CREATE TRIGGER EMPLOYEE_BI FOR EMPLOYEE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.EMP_NO IS NULL) THEN
    NEW.EMP_NO = GEN_ID(GEN_EMPLOYEE_ID,1);
END^
SET TERM ; ^

/* Data for table "DEPARTMENT" */
INSERT INTO DEPARTMENT (DEPT_NO, DEPARTMENT, HEAD_DEPT, LOCATION, PHONE_NO) VALUES (1, 'departamento1', 1, 'dsa', '555555');
INSERT INTO DEPARTMENT (DEPT_NO, DEPARTMENT, HEAD_DEPT, LOCATION, PHONE_NO) VALUES (2, 'departamento2', 2, 'dsa', '555555');
COMMIT;

/* Data for table "EMPLOYEE" */
INSERT INTO EMPLOYEE (EMP_NO, FIRST_NAME, LAST_NAME, PHONE_EXT, HIRE_DATE, DEPT_NO, FULL_NAME) VALUES (1, 'emp1', 'emp1lastname', '555', '2021-04-22 21:28:32', 1, 'emp1lastname, emp1');
INSERT INTO EMPLOYEE (EMP_NO, FIRST_NAME, LAST_NAME, PHONE_EXT, HIRE_DATE, DEPT_NO, FULL_NAME) VALUES (2, 'emp2', 'emp2lastname', '555', '2020-04-22 21:28:32', 1, 'emp2lastname, emp2');
INSERT INTO EMPLOYEE (EMP_NO, FIRST_NAME, LAST_NAME, PHONE_EXT, HIRE_DATE, DEPT_NO, FULL_NAME) VALUES (3, 'emp3', 'emp3lastname', '555', '2020-04-21 21:28:32', 1, 'emp3lastname, emp3');
INSERT INTO EMPLOYEE (EMP_NO, FIRST_NAME, LAST_NAME, PHONE_EXT, HIRE_DATE, DEPT_NO, FULL_NAME) VALUES (4, 'emp4', 'emp4lastname', '555', '2020-03-22 21:28:32', 2, 'emp4lastname, emp4');
INSERT INTO EMPLOYEE (EMP_NO, FIRST_NAME, LAST_NAME, PHONE_EXT, HIRE_DATE, DEPT_NO, FULL_NAME) VALUES (5, 'emp5', 'emp5lastname', '555', '2020-03-21 21:28:32', 2, 'emp5lastname, emp5');
INSERT INTO EMPLOYEE (EMP_NO, FIRST_NAME, LAST_NAME, PHONE_EXT, HIRE_DATE, DEPT_NO, FULL_NAME) VALUES (6, '??', '???', '9999', '2021-04-22 21:47:54', 2, '???, ??');
INSERT INTO EMPLOYEE (EMP_NO, FIRST_NAME, LAST_NAME, PHONE_EXT, HIRE_DATE, DEPT_NO, FULL_NAME) VALUES (7, 'halo Nuñet', ' Martínez ', '111', '2021-04-13 00:00:00', 2, ' Martínez , halo Nuñet');
INSERT INTO EMPLOYEE (EMP_NO, FIRST_NAME, LAST_NAME, PHONE_EXT, HIRE_DATE, DEPT_NO, FULL_NAME) VALUES (9, '? Ma Youyou, ?', '? Ma Youyou, ?', '999', '2021-04-22 21:49:53', 2, '? Ma Youyou, ?, ? Ma Youyou, ?');
INSERT INTO EMPLOYEE (EMP_NO, FIRST_NAME, LAST_NAME, PHONE_EXT, HIRE_DATE, DEPT_NO, FULL_NAME) VALUES (10, 'Maria de Jesús', '?????', '7979', '2021-04-06 00:00:00', 2, '?????, Maria de Jesús');
INSERT INTO EMPLOYEE (EMP_NO, FIRST_NAME, LAST_NAME, PHONE_EXT, HIRE_DATE, DEPT_NO, FULL_NAME) VALUES (11, 'MakSim', '???? ??ó?? ', '6454', '2021-04-22 21:54:32', 2, '???? ??ó?? , MakSim');
COMMIT;

